# Site settings
title: Omar Elshinnawey
email: elshinnaweyom@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog where I write anything that comes to my mind. Not necessarily technical.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.omardev.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: OmarAlShinnawey
github_username:  chefomar
name: Omar Elshinnawey
default_img: /assets/images/seo.png
website: https://omardev.net

# Build settings
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  style: compressed